"""
templates.py -- Pre-built COBOL program templates (factory pattern).

FACTORY PATTERN:
    Each function produces a COBOLProgram AST for a common program type.
    The caller provides domain-specific parameters (record name, field list,
    report types); the template fills in all the COBOL boilerplate (division
    structure, file handling, error checking, output protocol).

    This is how Layer 3 (LLM) will generate COBOL: the LLM chooses a
    template and provides parameters, rather than generating raw COBOL text.
    The template guarantees structural correctness; the LLM only needs to
    provide domain knowledge.

Program families in this project:
    CRUD    — Account-style programs (ACCOUNTS.cob pattern)
    Report  — Read-only programs (REPORTS.cob pattern)
    Batch   — Sequential file processors (TRANSACT.cob BATCH pattern)
"""

from typing import List, Dict, Optional
from .ast_nodes import (
    COBOLProgram, DataItem, ConditionItem, Paragraph, Statement,
    FileDeclaration, ProgramMetadata,
)


def crud_program(
    name: str,
    record_copybook: str,
    record_name: str,
    file_name: str,
    id_field: str,
    operations: List[str] = None,
) -> COBOLProgram:
    """Generate an ACCOUNTS-style CRUD program.

    Produces a program with:
        - File I/O for the specified record type
        - EVALUATE-based operation dispatcher
        - CREATE, READ, UPDATE, LIST, CLOSE operations
        - Pipe-delimited DISPLAY output protocol
        - Error handling with status codes

    Args:
        name: Program name (e.g., "CUSTOMERS")
        record_copybook: Copybook file (e.g., "CUSTREC.cpy")
        record_name: Top-level record name (e.g., "CUSTOMER-RECORD")
        file_name: Physical file name (e.g., "CUSTOMERS.DAT")
        id_field: Primary key field (e.g., "CUST-ID")
        operations: List of operations (default: CREATE, READ, UPDATE, LIST, CLOSE)

    Returns:
        COBOLProgram AST ready for code generation.
    """
    if operations is None:
        operations = ["CREATE", "READ", "UPDATE", "LIST", "CLOSE"]

    logical_file = f"{name}-FILE"

    metadata = ProgramMetadata(
        program_id=name,
        author="cobol_codegen",
        purpose=f"CRUD operations for {record_name}",
        compile_command=f"cobc -x -free -I ../copybooks {name}.cob -o ../bin/{name}",
    )

    file_decl = FileDeclaration(
        logical_name=logical_file,
        physical_name=file_name,
        organization="LINE SEQUENTIAL",
        status_var="WS-FILE-STATUS",
        copybook=record_copybook,
        record_name=record_name,
    )

    # Working storage items
    ws_items = [
        DataItem(level=1, name="WS-FILE-STATUS", pic="XX", value="SPACES",
                 conditions=[
                     ConditionItem(name="WS-FILE-OK", value="00"),
                     ConditionItem(name="WS-FILE-EOF", value="10"),
                 ]),
        DataItem(level=1, name="WS-OPERATION", pic="X(10)", value="SPACES"),
        DataItem(level=1, name="WS-SEARCH-ID", pic="X(10)", value="SPACES"),
        DataItem(level=1, name="WS-RECORD-COUNT", pic="9(4)", value="0"),
    ]

    # Build paragraphs
    paragraphs = []

    # MAIN-PROGRAM
    main_stmts = [Statement(verb="EVALUATE", raw_text="EVALUATE WS-OPERATION")]
    for op in operations:
        main_stmts.append(Statement(verb="WHEN", raw_text=f'WHEN "{op}"'))
        main_stmts.append(Statement(verb="PERFORM", raw_text=f"    PERFORM {op}-OPERATION", target=f"{op}-OPERATION"))
    main_stmts.append(Statement(verb="WHEN", raw_text='WHEN OTHER'))
    main_stmts.append(Statement(verb="DISPLAY", raw_text='    DISPLAY "RESULT|03|Unknown operation"'))
    main_stmts.append(Statement(verb="END-EVALUATE", raw_text="END-EVALUATE"))
    main_stmts.append(Statement(verb="STOP", raw_text="STOP RUN"))
    paragraphs.append(Paragraph(name="MAIN-PROGRAM", statements=main_stmts))

    # Operation paragraphs (stubs)
    for op in operations:
        stmts = [
            Statement(verb="DISPLAY", raw_text=f'DISPLAY "RESULT|00|{op} completed"'),
        ]
        paragraphs.append(Paragraph(
            name=f"{op}-OPERATION",
            statements=stmts,
            comment=f"{op} operation for {record_name}",
        ))

    return COBOLProgram(
        metadata=metadata,
        files=[file_decl],
        working_storage=ws_items,
        paragraphs=paragraphs,
        copybooks=[record_copybook],
        header_comments=[
            f"{'=' * 64}",
            f"{name}.cob -- CRUD operations for {record_name}",
            f"Generated by cobol_codegen templates.py",
            f"Compile: {metadata.compile_command}",
            f"{'=' * 64}",
        ],
    )


def report_program(
    name: str,
    input_files: List[Dict[str, str]],
    report_types: List[str],
) -> COBOLProgram:
    """Generate a REPORTS-style read-only program.

    Produces a program that reads input files and generates formatted reports.

    Args:
        name: Program name (e.g., "CUSTREPORT")
        input_files: List of dicts with keys: logical_name, physical_name, copybook
        report_types: List of report names (e.g., ["STATEMENT", "SUMMARY"])

    Returns:
        COBOLProgram AST ready for code generation.
    """
    metadata = ProgramMetadata(
        program_id=name,
        author="cobol_codegen",
        purpose=f"Report generator: {', '.join(report_types)}",
    )

    files = []
    for f in input_files:
        files.append(FileDeclaration(
            logical_name=f['logical_name'],
            physical_name=f['physical_name'],
            organization="LINE SEQUENTIAL",
            status_var="WS-FILE-STATUS",
            copybook=f.get('copybook', ''),
        ))

    ws_items = [
        DataItem(level=1, name="WS-FILE-STATUS", pic="XX", value="SPACES",
                 conditions=[
                     ConditionItem(name="WS-FILE-OK", value="00"),
                     ConditionItem(name="WS-FILE-EOF", value="10"),
                 ]),
        DataItem(level=1, name="WS-REPORT-TYPE", pic="X(10)", value="SPACES"),
        DataItem(level=1, name="WS-RECORD-COUNT", pic="9(6)", value="0"),
    ]

    paragraphs = [
        Paragraph(name="MAIN-PROGRAM", statements=[
            Statement(verb="EVALUATE", raw_text="EVALUATE WS-REPORT-TYPE"),
            *[Statement(verb="WHEN", raw_text=f'WHEN "{rt}"\n                PERFORM GENERATE-{rt}')
              for rt in report_types],
            Statement(verb="END-EVALUATE", raw_text="END-EVALUATE"),
            Statement(verb="STOP", raw_text="STOP RUN"),
        ]),
    ]

    for rt in report_types:
        paragraphs.append(Paragraph(
            name=f"GENERATE-{rt}",
            statements=[
                Statement(verb="DISPLAY", raw_text=f'DISPLAY "{rt}|Report generated"'),
                Statement(verb="DISPLAY", raw_text='DISPLAY "RESULT|00"'),
            ],
            comment=f"Generate {rt} report",
        ))

    return COBOLProgram(
        metadata=metadata,
        files=files,
        working_storage=ws_items,
        paragraphs=paragraphs,
        header_comments=[
            f"{'=' * 64}",
            f"{name}.cob -- Report generator",
            f"Reports: {', '.join(report_types)}",
            f"{'=' * 64}",
        ],
    )


def batch_program(
    name: str,
    input_file: str,
    input_copybook: str,
    record_name: str,
    processing_description: str = "Process records",
) -> COBOLProgram:
    """Generate a TRANSACT-style batch processing program.

    Produces a program that reads a sequential input file record by record,
    processes each one, and produces a summary.

    Args:
        name: Program name (e.g., "PAYROLL")
        input_file: Physical file name (e.g., "PAYROLL-INPUT.DAT")
        input_copybook: Copybook for input records
        record_name: Top-level record name
        processing_description: Human-readable description of processing

    Returns:
        COBOLProgram AST ready for code generation.
    """
    metadata = ProgramMetadata(
        program_id=name,
        author="cobol_codegen",
        purpose=processing_description,
    )

    file_decl = FileDeclaration(
        logical_name=f"{name}-INPUT",
        physical_name=input_file,
        organization="LINE SEQUENTIAL",
        status_var="WS-FILE-STATUS",
        copybook=input_copybook,
        record_name=record_name,
    )

    ws_items = [
        DataItem(level=1, name="WS-FILE-STATUS", pic="XX", value="SPACES",
                 conditions=[
                     ConditionItem(name="WS-FILE-OK", value="00"),
                     ConditionItem(name="WS-FILE-EOF", value="10"),
                 ]),
        DataItem(level=1, name="WS-RECORD-COUNT", pic="9(6)", value="0"),
        DataItem(level=1, name="WS-SUCCESS-COUNT", pic="9(6)", value="0"),
        DataItem(level=1, name="WS-FAIL-COUNT", pic="9(6)", value="0"),
    ]

    paragraphs = [
        Paragraph(name="MAIN-PROGRAM", statements=[
            Statement(verb="PERFORM", raw_text="PERFORM OPEN-INPUT"),
            Statement(verb="PERFORM", raw_text="PERFORM PROCESS-RECORDS"),
            Statement(verb="PERFORM", raw_text="PERFORM CLOSE-INPUT"),
            Statement(verb="PERFORM", raw_text="PERFORM DISPLAY-SUMMARY"),
            Statement(verb="STOP", raw_text="STOP RUN"),
        ]),
        Paragraph(name="OPEN-INPUT", statements=[
            Statement(verb="OPEN", raw_text=f"OPEN INPUT {name}-INPUT"),
            Statement(verb="IF", raw_text='IF NOT WS-FILE-OK\n                DISPLAY "ERROR|FILE-OPEN|" WS-FILE-STATUS\n                STOP RUN\n            END-IF'),
        ], comment="Open input file for sequential reading"),
        Paragraph(name="PROCESS-RECORDS", statements=[
            Statement(verb="PERFORM", raw_text=f"PERFORM READ-NEXT-RECORD\n            PERFORM UNTIL WS-FILE-EOF\n                PERFORM PROCESS-ONE-RECORD\n                PERFORM READ-NEXT-RECORD\n            END-PERFORM"),
        ], comment="Main processing loop"),
        Paragraph(name="READ-NEXT-RECORD", statements=[
            Statement(verb="READ", raw_text=f"READ {name}-INPUT\n                AT END SET WS-FILE-EOF TO TRUE\n            END-READ"),
        ]),
        Paragraph(name="PROCESS-ONE-RECORD", statements=[
            Statement(verb="ADD", raw_text="ADD 1 TO WS-RECORD-COUNT"),
            Statement(verb="ADD", raw_text="ADD 1 TO WS-SUCCESS-COUNT"),
        ], comment=processing_description),
        Paragraph(name="CLOSE-INPUT", statements=[
            Statement(verb="CLOSE", raw_text=f"CLOSE {name}-INPUT"),
        ]),
        Paragraph(name="DISPLAY-SUMMARY", statements=[
            Statement(verb="DISPLAY", raw_text='DISPLAY "SUMMARY|" WS-RECORD-COUNT "|" WS-SUCCESS-COUNT "|" WS-FAIL-COUNT'),
            Statement(verb="DISPLAY", raw_text='DISPLAY "RESULT|00"'),
        ], comment="Display batch processing summary"),
    ]

    return COBOLProgram(
        metadata=metadata,
        files=[file_decl],
        working_storage=ws_items,
        paragraphs=paragraphs,
        header_comments=[
            f"{'=' * 64}",
            f"{name}.cob -- Batch processor",
            f"{processing_description}",
            f"{'=' * 64}",
        ],
    )


def copybook_record(
    name: str,
    fields: List[Dict[str, str]],
    record_name: Optional[str] = None,
) -> List[DataItem]:
    """Generate a copybook record layout from a field specification.

    Args:
        name: Copybook name (used for comments)
        fields: List of dicts with keys: name, pic, and optional: value, comment
        record_name: Top-level 01 record name (default: derived from name)

    Returns:
        List of DataItem nodes (01 group + 05 children) for generator.generate_copybook()
    """
    if record_name is None:
        record_name = f"{name}-RECORD"

    children = []
    for f in fields:
        item = DataItem(
            level=5,
            name=f['name'],
            pic=f['pic'],
            value=f.get('value'),
            comment=f.get('comment', ''),
        )
        # Add 88-level conditions if specified
        for cond in f.get('conditions', []):
            item.conditions.append(ConditionItem(
                name=cond['name'],
                value=cond['value'],
                thru_value=cond.get('thru_value'),
            ))
        children.append(item)

    group = DataItem(
        level=1,
        name=record_name,
        children=children,
    )
    return [group]
